### ISSUE TITLE
🐛 Preview not working

### ISSUE THREAD

**Issue by khromov** [SvelteLab/SvelteLab#248]
### Describe the bug

I can't seem to run `npm run preview`

### Reproduction

1. Go to https://www.sveltelab.dev/
2. Close out of the existing dev command with Ctrl+C or equivalent
3. Press the run button next to `npm run preview` or type it manually in the console

### Expected behavior

It should work, but instead I get this in Firefox:

```
> sveltelab-basic@0.0.1 preview
> vite preview


error when starting preview server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/httpswwwsveltelabdev-dcnb-sdd2ysxr/.svelte-kit/output/server/internal.js' imported from /home/httpswwwsveltelabdev-dcnb-sdd2ysxr/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js
    at get (https://httpswwwsveltelabdev-dcnb-sdd2ysxr.w-corp.staticblitz.com/blitz.e809191e.js:35:385021)
    at  (/home/httpswwwsveltelabdev-dcnb-sdd2ysxr/node_modules/vite/dist/node/cli.js:900:129)
```

And this in Chrome:

```
> sveltelab-basic@0.0.1 preview
> vite preview


error when starting preview server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/httpswwwsveltelabdev-dcnb/.svelte-kit/output/server/internal.js' imported from /home/httpswwwsveltelabdev-dcnb/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js
    at InternalError.get (https://httpswwwsveltelabdev-dcnb.w-corp.staticblitz.com/blitz.e809191e.js:35:385021)
    at CAC.eval (file:///home/httpswwwsveltelabdev-dcnb/node_modules/vite/dist/node/cli.js:900:131
```

**Comment by paoloricciuti** [comment]
To run preview you first need to run build (that's not in SvelteLab, that's just how sveltekit works)

**Comment by khromov** [comment]
That explains a thing or two, thanks for the quick response!

**Comment by SvelteLab** [comment]
> That explains a thing or two, thanks for the quick response!

Glad it helped 😁
